-- ShopDesk OS operational PostgreSQL schema (reference only; do not execute in production).
create extension if not exists pgcrypto;

create table stores (id uuid primary key default gen_random_uuid(), organization_id uuid not null, installation_id uuid not null, name text not null, slug text not null, system_name text, accent_color text, rnc text, phone text, active boolean not null default true, created_at timestamptz not null default now(), unique(organization_id, installation_id, slug), unique(id, organization_id, installation_id));
create table app_profiles (id uuid primary key, organization_id uuid not null, installation_id uuid not null, full_name text not null, role text not null, active boolean not null default true, created_at timestamptz not null default now(), unique(id, organization_id, installation_id));
create table store_users (store_id uuid not null, user_id uuid not null, organization_id uuid not null, installation_id uuid not null, role text not null, permissions jsonb not null default '[]', primary key(store_id,user_id), foreign key(store_id,organization_id,installation_id) references stores(id,organization_id,installation_id), foreign key(user_id,organization_id,installation_id) references app_profiles(id,organization_id,installation_id));

create table categories (id uuid primary key default gen_random_uuid(), organization_id uuid not null, installation_id uuid not null, store_id uuid not null, name text not null, active boolean not null default true, unique(store_id,name), foreign key(store_id,organization_id,installation_id) references stores(id,organization_id,installation_id));
create table product_types (id uuid primary key default gen_random_uuid(), organization_id uuid not null, installation_id uuid not null, store_id uuid not null, name text not null, active boolean not null default true, unique(store_id,name), foreign key(store_id,organization_id,installation_id) references stores(id,organization_id,installation_id));
create table products (id uuid primary key default gen_random_uuid(), organization_id uuid not null, installation_id uuid not null, store_id uuid not null, category_id uuid references categories(id), product_type_id uuid references product_types(id), name text not null, sku text, barcode text, cost numeric(14,2) not null default 0 check(cost>=0), sale_price numeric(14,2) not null default 0 check(sale_price>=0), stock numeric(14,3) not null default 0, active boolean not null default true, specs jsonb not null default '{}', created_at timestamptz not null default now(), updated_at timestamptz not null default now(), foreign key(store_id,organization_id,installation_id) references stores(id,organization_id,installation_id), unique(store_id,sku), unique(store_id,barcode));
create index products_tenant_store_active_idx on products(organization_id,installation_id,store_id,active,name);
create table product_images (id uuid primary key default gen_random_uuid(), organization_id uuid not null, installation_id uuid not null, store_id uuid not null, product_id uuid not null references products(id) on delete cascade, image_url text not null, is_primary boolean not null default false, sort_order integer not null default 0, foreign key(store_id,organization_id,installation_id) references stores(id,organization_id,installation_id));

create table customers (id uuid primary key default gen_random_uuid(), organization_id uuid not null, installation_id uuid not null, store_id uuid not null, full_name text not null, document text, phone text, address text, email text, active boolean not null default true, created_at timestamptz not null default now(), foreign key(store_id,organization_id,installation_id) references stores(id,organization_id,installation_id));
create index customers_store_document_idx on customers(store_id,document);
create table suppliers (id uuid primary key default gen_random_uuid(), organization_id uuid not null, installation_id uuid not null, store_id uuid not null, name text not null, rnc text, phone text, email text, address text, active boolean not null default true, foreign key(store_id,organization_id,installation_id) references stores(id,organization_id,installation_id));
create table payment_methods (id uuid primary key default gen_random_uuid(), organization_id uuid not null, installation_id uuid not null, store_id uuid not null, name text not null, kind text not null, active boolean not null default true, unique(store_id,name), foreign key(store_id,organization_id,installation_id) references stores(id,organization_id,installation_id));

create table purchases (id uuid primary key default gen_random_uuid(), organization_id uuid not null, installation_id uuid not null, store_id uuid not null, supplier_id uuid references suppliers(id), invoice_number text, status text not null default 'draft' check(status in ('draft','received','cancelled')), subtotal numeric(14,2) not null default 0, tax numeric(14,2) not null default 0, total numeric(14,2) not null default 0, received_at timestamptz, created_by uuid, created_at timestamptz not null default now(), foreign key(store_id,organization_id,installation_id) references stores(id,organization_id,installation_id));
create table purchase_items (id uuid primary key default gen_random_uuid(), purchase_id uuid not null references purchases(id) on delete cascade, product_id uuid not null references products(id), quantity numeric(14,3) not null check(quantity>0), unit_cost numeric(14,2) not null check(unit_cost>=0), tax numeric(14,2) not null default 0, total numeric(14,2) not null check(total>=0));
create table cash_registers (id uuid primary key default gen_random_uuid(), organization_id uuid not null, installation_id uuid not null, store_id uuid not null, opened_by uuid not null, opened_at timestamptz not null default now(), closed_by uuid, closed_at timestamptz, opening_amount numeric(14,2) not null default 0, closing_amount numeric(14,2), status text not null default 'open' check(status in ('open','closed')), foreign key(store_id,organization_id,installation_id) references stores(id,organization_id,installation_id));
create table sales (id uuid primary key default gen_random_uuid(), organization_id uuid not null, installation_id uuid not null, store_id uuid not null, customer_id uuid references customers(id), cash_register_id uuid references cash_registers(id), payment_method_id uuid references payment_methods(id), invoice_number text, status text not null default 'completed', subtotal numeric(14,2) not null default 0, discount numeric(14,2) not null default 0, itbis numeric(14,2) not null default 0, total numeric(14,2) not null default 0, amount_paid numeric(14,2) not null default 0, balance_due numeric(14,2) not null default 0, ncf text, fiscal_receipt_type text, fiscal_status text, fiscal_customer_name text, fiscal_customer_rnc text, fiscal_customer_phone text, fiscal_customer_address text, fiscal_customer_source text, fiscal_notes text, ecf_security_code text, ecf_qr_url text, created_by uuid, created_at timestamptz not null default now(), foreign key(store_id,organization_id,installation_id) references stores(id,organization_id,installation_id));
create unique index sales_store_ncf_unique on sales(store_id,ncf) where ncf is not null;
create index sales_tenant_store_created_idx on sales(organization_id,installation_id,store_id,created_at desc);
create table sale_items (id uuid primary key default gen_random_uuid(), sale_id uuid not null references sales(id) on delete cascade, product_id uuid references products(id), product_name text not null, sku text, quantity numeric(14,3) not null check(quantity>0), cost numeric(14,2) not null default 0, unit_price numeric(14,2) not null, tax numeric(14,2) not null default 0, total numeric(14,2) not null, imei text);
create table credit_notes (id uuid primary key default gen_random_uuid(), organization_id uuid not null, installation_id uuid not null, store_id uuid not null, sale_id uuid not null references sales(id), credit_note_number text not null, fiscal_number text, reason text, status text not null default 'issued', subtotal numeric(14,2) not null default 0, tax_amount numeric(14,2) not null default 0, total numeric(14,2) not null default 0, available_balance numeric(14,2) not null default 0 check(available_balance>=0), created_by uuid, created_at timestamptz not null default now(), unique(store_id,credit_note_number), foreign key(store_id,organization_id,installation_id) references stores(id,organization_id,installation_id));
create table credit_note_items (id uuid primary key default gen_random_uuid(), credit_note_id uuid not null references credit_notes(id) on delete cascade, sale_item_id uuid not null references sale_items(id), product_id uuid not null references products(id), quantity numeric(14,3) not null check(quantity>0), restock_quantity numeric(14,3) not null default 0, damaged_quantity numeric(14,3) not null default 0, unit_price numeric(14,2) not null, tax_amount numeric(14,2) not null default 0, line_total numeric(14,2) not null, check(restock_quantity+damaged_quantity=quantity));
create table sale_payments (id uuid primary key default gen_random_uuid(), organization_id uuid not null, installation_id uuid not null, store_id uuid not null, sale_id uuid not null references sales(id), payment_method_id uuid references payment_methods(id), credit_note_id uuid references credit_notes(id), payment_method text not null, amount numeric(14,2) not null check(amount>0), created_at timestamptz not null default now(), foreign key(store_id,organization_id,installation_id) references stores(id,organization_id,installation_id));
create table cash_movements (id uuid primary key default gen_random_uuid(), organization_id uuid not null, installation_id uuid not null, store_id uuid not null, cash_register_id uuid references cash_registers(id), type text not null, amount numeric(14,2) not null check(amount>0), reference_type text, reference_id uuid, notes text, created_by uuid, created_at timestamptz not null default now(), foreign key(store_id,organization_id,installation_id) references stores(id,organization_id,installation_id));

create table quotes (id uuid primary key default gen_random_uuid(), organization_id uuid not null, installation_id uuid not null, store_id uuid not null, quote_number text not null, status text not null default 'draft', subtotal numeric(14,2) not null default 0, tax numeric(14,2) not null default 0, total numeric(14,2) not null default 0, expires_at timestamptz, created_at timestamptz not null default now(), unique(store_id,quote_number), foreign key(store_id,organization_id,installation_id) references stores(id,organization_id,installation_id));
create table quote_customers (quote_id uuid primary key references quotes(id) on delete cascade, customer_id uuid references customers(id), full_name text not null, document text, phone text, address text);
create table quote_items (id uuid primary key default gen_random_uuid(), quote_id uuid not null references quotes(id) on delete cascade, product_id uuid references products(id), product_name text not null, quantity numeric(14,3) not null check(quantity>0), unit_price numeric(14,2) not null, tax numeric(14,2) not null default 0, total numeric(14,2) not null);
create table product_exchanges (id uuid primary key default gen_random_uuid(), organization_id uuid not null, installation_id uuid not null, store_id uuid not null, sale_id uuid references sales(id), credit_note_id uuid references credit_notes(id), notes text, created_by uuid, created_at timestamptz not null default now(), foreign key(store_id,organization_id,installation_id) references stores(id,organization_id,installation_id));
create table product_returns (id uuid primary key default gen_random_uuid(), organization_id uuid not null, installation_id uuid not null, store_id uuid not null, sale_id uuid references sales(id), credit_note_id uuid references credit_notes(id), product_id uuid references products(id), quantity numeric(14,3) not null check(quantity>0), reason text, created_at timestamptz not null default now(), foreign key(store_id,organization_id,installation_id) references stores(id,organization_id,installation_id));
create table damaged_inventory (id uuid primary key default gen_random_uuid(), organization_id uuid not null, installation_id uuid not null, store_id uuid not null, product_id uuid not null references products(id), sale_item_id uuid references sale_items(id), credit_note_id uuid references credit_notes(id), quantity numeric(14,3) not null check(quantity>0), status text not null default 'damaged', reason text, created_at timestamptz not null default now(), foreign key(store_id,organization_id,installation_id) references stores(id,organization_id,installation_id));
create table inventory_movements (id uuid primary key default gen_random_uuid(), organization_id uuid not null, installation_id uuid not null, store_id uuid not null, product_id uuid not null references products(id), type text not null, quantity numeric(14,3) not null, reference_type text, reference_id uuid, created_by uuid, created_at timestamptz not null default now(), foreign key(store_id,organization_id,installation_id) references stores(id,organization_id,installation_id));
create table employees (id uuid primary key default gen_random_uuid(), organization_id uuid not null, installation_id uuid not null, store_id uuid not null, auth_user_id uuid, full_name text not null, role text not null, active boolean not null default true, created_at timestamptz not null default now(), foreign key(store_id,organization_id,installation_id) references stores(id,organization_id,installation_id));
create table audit_logs (id uuid primary key default gen_random_uuid(), organization_id uuid not null, installation_id uuid not null, store_id uuid, user_id uuid, module text not null, action text not null, detail text, metadata jsonb not null default '{}', created_at timestamptz not null default now());
create table dgii_contributors (document text primary key, registered_name text not null, taxpayer_type text check(taxpayer_type in ('NORMAL','RST')), updated_at timestamptz not null default now());
create table ncf_receipts (id uuid primary key default gen_random_uuid(), organization_id uuid not null, installation_id uuid not null, store_id uuid not null, receipt_type text not null, prefix text not null, range_start bigint not null, range_end bigint not null, next_number bigint not null, expires_at date, active boolean not null default true, check(next_number between range_start and range_end+1), unique(store_id,receipt_type,active), foreign key(store_id,organization_id,installation_id) references stores(id,organization_id,installation_id));

-- Transactional services must validate tenant scope, then use a transaction and
-- SELECT ... FOR UPDATE for stock, NCF allocation, and source sale/purchase rows.
